/* Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/


var findTheDifference = function(s, t) {
  // iterate over s
  var sCount = {}
  for (var i = 0; i < s.length; i++) {
    if (!sCount[s[i]]) {
      sCount[s[i]] = 1;
    } else {
      sCount[s[i]]++;
    }
  }

  //iterate over t
  var tCount = {}
  for (var i = 0; i < t.length; i++) {
    if (!sCount[t[i]]) return t[i];
    if (!tCount[t[i]]) {
      tCount[t[i]] = 1;
    } else {
      tCount[t[i]]++;
    }
  }
  
  for (key in sCount) {
    if (sCount[key] !== tCount[key]) return key;
  }
};

console.log(findTheDifference('asddf', 'dfdsda'))